from pathlib import Path
import csv,json,hashlib,datetime,collections
C=Path('/home/kaiwen/research/LegSA-GINS-WORKTREES/audit-code-xbpg-20261001');B=C/'docs/paper_rebuild/V3_STORY_20261004';S=Path('/mnt/g/LegSA-GINS-project/clean_rebuild_202607/stages/CLEAN8_PROTOCOL_V3');SG=Path('/mnt/g/LegSA-GINS-project/clean_rebuild_202607/stages/FGO_SEGMENTED_DIAGNOSTIC_20261004T100449Z');A=Path('/mnt/g/LegSA-GINS-project/审查_20261003')
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def wc(name,rr):
 rr=list(rr);assert rr;p=B/name;assert not p.exists();p.parent.mkdir(exist_ok=True)
 with p.open('x',newline='',encoding='utf-8') as f:w=csv.DictWriter(f,fieldnames=list(rr[0]));w.writeheader();w.writerows(rr)
 return len(rr)
before={str(p.relative_to(B)):sha(p) for p in B.rglob('*') if p.is_file() and 'COMPARISON_SOURCES' not in p.parts and p.name not in ['TASK_LEDGER.csv','METRIC_LEDGER.csv','NATIVE_ACTION_LEDGER.csv']};assert len(before)==56
sources=[];copied={}
def capture(name,p,context,copy=True):
 p=Path(p);hh=sha(p);rr=list(csv.DictReader(p.open(encoding='utf-8-sig'))) if p.suffix=='.csv' else None
 if copy:
  q=B/'COMPARISON_SOURCES'/name;q.parent.mkdir(exist_ok=True)
  if q.exists():assert sha(q)==hh, 'Only exact partial fourth-block copies may resume'
  else:q.write_bytes(p.read_bytes())
  assert sha(q)==hh;copied[str(q.relative_to(B))]=len(rr) if rr is not None else 'JSON_METADATA'
 sources.append({'copied_name':name if copy else 'PIN_ONLY','actual_path':str(p),'sha256_before':hh,'bytes':p.stat().st_size,'data_rows':len(rr) if rr is not None else '', 'columns':len(rr[0]) if rr else '', 'scientific_time_context':context,'read_mode':'FULL_STRUCTURED_MACHINE_READ; semantic selected scopes recorded separately'})
 return rr
capture('ORIGINAL_V3_MAIN_TABLE_V3.csv',S/'07_AGGREGATE/MAIN_TABLE_V3.csv','Original V3 historical table. 21 unavailable external placeholders apply to its original assembly time, not later actual execution.')
capture('ORIGINAL_V3_MAIN_TABLE_V2.csv',S/'07_AGGREGATE/MAIN_TABLE_V2.csv','Parallel original evaluation point contract; do not merge with v3 metrics.')
reg=capture('ORIGINAL_EXTERNAL_REGISTRY.csv',C/'docs/paper_rebuild/hext/HX_INVENTORY.csv','Original 23 registered method/config identities; not 23 unique successful complete papers.')
old=capture('HISTORICAL_20261003_ENHANCED_INVENTORY.csv',A/'HORIZONTAL_METHOD_INVENTORY.csv','Historical read/audit facts; newer EXT V2 and FGO are separately identified, no old label overwritten.')
assert len(reg)==len(old)==23 and {r['method_id'] for r in reg}=={r['method_id'] for r in old}
ext=capture('EXT_V2_COMPARISON_TABLE.csv',C/'docs/paper_rebuild/hext/EXT_REPRODUCTION/v2_fix/COMPARISON_TABLE.csv','Nine fresh RAW_REPRO_V2_TECH_RETRY_2 executions, guardless saved source. Three raw methods + four frozen RTKLIB conditions, different support roles.')
capture('EXT_V2_COMMON_SUPPORT_ALL.csv',C/'docs/paper_rebuild/hext/EXT_REPRODUCTION/v2_fix/COMMON_SUPPORT_ALL.csv','450 common-support records retain empty and fixed-not-applicable groups; not identical sensor model.')
capture('EXT_V1_V2_SAME_METHOD_COMMON_SUPPORT.csv',C/'docs/paper_rebuild/hext/EXT_REPRODUCTION/v2_fix/V1_V2_SAME_METHOD_COMMON_SUPPORT.csv','27 records compare existing old/new same method same time keys; no new solver.')
fgo=capture('FGO_STRICT_METRICS.csv',C/'docs/paper_rebuild/hext/FGO_REPRODUCTION_FIX_20261004/METRICS.csv','Strict one A1/no restart OiSAM: B275 H0 O55; W/GNC full batch six runs. Native point contracts differ.')
capture('FGO_STRICT_COMPARISON_TABLE.csv',C/'docs/paper_rebuild/hext/FGO_REPRODUCTION_FIX_20261004/COMPARISON_TABLE.csv','100 historical application rows. Reused EXT values belong original source generation; latest EXT V2 remains separate, no silent refresh.')
capture('RTKLIB_HX07R_MANUSCRIPT_ROWS.csv',C/'docs/paper_rebuild/hext/HX07R/HX07R_MANUSCRIPT_ROWS.csv','V0 frozen/control reproduced, V1 extra; V0E/V2 and old V0-convbin separately retained.')
capture('RTKLIB_HX07R_SUPPLEMENT_ROWS.csv',C/'docs/paper_rebuild/hext/HX07R/HX07R_SUPPLEMENT_ROWS.csv','RTKLIB condition variants, native/fixed/held support kept distinct.')
capture('HX05_HISTORICAL_MANUSCRIPT.csv',C/'docs/paper_rebuild/hext/HX05/EXTERNAL_THREE_SEQUENCE_MANUSCRIPT.csv','Historical five-category report contains old EXT backend results. No claim these are latest EXT V2.')
capture('HX05_HISTORICAL_SUPPLEMENT.csv',C/'docs/paper_rebuild/hext/HX05/EXTERNAL_THREE_SEQUENCE_SUPPLEMENT.csv','Official Hartley and LC01/EXT05C calibrated/initialization variants preserve original role and caveats.')
nom=capture('EXT_NOMINAL_QUANTITY_SUMMARY.csv',C/'docs/paper_rebuild/EXT_MEASURAND_20261004/SUMMARY.csv','New offline nominal quantity diagnostic on same 7689 old saved valid keys. Original nine native/evaluation unchanged; mounting/shared-reference still conditional.')
seg=[]
for seq in ['BY2','BY2H','BY2O']:
 rr=capture('FGO_SEGMENTED_'+seq+'_METRICS.csv',SG/'evaluation'/seq/'METRICS.csv','New3 Oi native +6 strict W/GNC reused, all native sealed before3offline. Same GNSS1 point; primary excludes every prior-only init, secondary separately includes them.');assert len(rr)==12;seg.extend(rr)
 capture('FGO_SEGMENTED_'+seq+'_EVALUATION_METADATA.json',SG/'evaluation'/seq/'EVALUATION.json','Frozen reference/anchor/native/input hashes, common nominal keys and source before/after declarations. Structured metadata only.',False)
for n,expected in [('PREREGISTRATION.json','20a4ac31da1ef0cb0759e23bac60eb059373e1e7e9fa2dcff52fd065d0238b24'),('ALL_NATIVE_SEALED.json','3af7f0c6d010d83c2ea6763f97189ae702cb761d374cb7410ce9fd51c14423ab'),('ALL_OFFLINE_COMPLETE.json','374cee2501ab7fcfa2432567e056eb9dd6842c7db8a1bda989b5027bce1c815d')]:
 assert sha(SG/n)==expected;capture('FGO_SEGMENTED_'+n,SG/n,'New explicit segmented diagnostic identity; never overwrite strict H0/O55.',True)
for rel,context in [('docs/paper_rebuild/hext/EXT_REPRODUCTION/v2_fix/FINAL_EXECUTION_RECEIPT.json','EXT V2 nine native source/input/access+offline metadata'),('docs/paper_rebuild/hext/EXT_REPRODUCTION/v2_fix/NATIVE_ACCESS_AUDIT.json','All15669 old native records,9100valid; raw/reference access audit'),('docs/paper_rebuild/FGO_COMPLETE_AUDIT_20261004/COMPLIANCE_MATRIX.csv','45 key selected-paper implementation correspondences; complete author experiment not claimed'),('docs/paper_rebuild/FGO_COMPLETE_AUDIT_20261004/EVIDENCE_IDENTITY.json','Source overlays and historical actual run identity'),('docs/paper_rebuild/EXT_MEASURAND_20261004/RESULT_RECEIPT.json','same-key post-native offline quantity explanation'),('docs/paper_rebuild/EXT_MEASURAND_20261004/ROOT_OFFLINE_RESULT_REVIEW.json','independent all-key arithmetic/access closure')]:capture('',C/rel,context,False)
for n in ['EXT_HEADING_POST_RESULT_REPAIR_RECEIPT.json','EXT_HEADING_POST_RESULT_INDEPENDENT_PEER_REVIEW.json','FGO_SEGMENTED_INDEPENDENT_REVIEW.json','FGO_SEGMENTED_ROOT_INDEPENDENT_REVIEW.json']:
 p=Path('/mnt/g/LegSA-GINS-project/修复_20261004')/n;assert p.exists();capture('',p,'Independent declared review/identity gate; no scientist rerun implied.',False)
# New reader inventory preserves every historical registry id and adds clearly identified conditions/extra methods.
updates={
 'EXT01':('Teunissen C-LAMBDA compass (independent core)','DD code/phase GPS L1 + project 0.350m length','Raw code SPP positions, no IMU/A1/reference solver input','3D baseline + integer ambiguities','lateral baseline horizontal projection +90deg; no navigation position','No position POI; heading measurand separate from Euler','V2 raw9 subset; valid980/1059/1173 of1370/1350/1885; yawdiagnostic85.015472/89.127388/81.273465deg','Core ILS/spherical optimization, strict B&B budgets; no ambiguity acceptance/true-integer oracle; not author full-system/experiment replay'),
 'EXT02':('Liu et al. C-WLS compass (single-baseline independent core)','Same raw GPS L1 code/phase + project length','Raw code SPP, no IMU/A1/reference','single baseline direction + derived integers','projected lateral-baseline heading','heading-only, no POI position','V2 valid961/1029/1210; yaw85.179795/89.192923/81.486071deg','Single-baseline Algorithm1/2; full unique candidate pool and reject-whole-epoch if any noncompletion are engineering policy, not disclosed author parameter; no multiantenna full-axis replay'),
 'EXT03':('Yang et al. baseline-length-constrained DD-KF/MLAMBDA','Raw GPS L1/L2 +BDS B1/B2 DD code/phase + project length','Raw code SPP baseline reset, no inertial integration/A1/reference','baseline + continuing DD ambiguity states','projected lateral-baseline heading, accepted ratio subset separate','heading-only, no navigation POI','V2 valid541/467/269; ratiofixed78/70/5; yaw79.931845/63.994556/103.754200deg','True DD-KF/length row/MLAMBDA/ratio; undisclosed F/Q and baseline resets explicitly project assumptions; no integer truth. Not author full original experimental program'),
 'EXT04':('Wu et al. FAR/PAR ambiguity module diagnostic','Old raw DD functional backend','Project SPP baseline; old shared satellite-time model','ambiguity/baseline FAR/PAR only','heading module; no INS/misalignment state','no navigation position','zero accepted FAR/PAR three sequences retained','Not full GNSS/INS/misalignment method; not upgraded with new EXT V2 backend'),
 'RTKLIB_UNMODIFIED_MOVING_BASE':('RTKLIB moving-base (V0 frozen condition)','Two reconstructed receiver RINEX observations + old receiver nav, L1/L2, navsys33','Official single-point initialization from each receiver; no A1/IMU','official raw-GNSS relative baseline/ambiguities','projected moving-baseline heading, native/Q1/Q2/held distinct','heading-only, no GNSS/INS output','HX07R12native13eval; V0valid153/179/112,RMSE14.566166/27.011169/23.138950deg','Official RTKLIB2.4.3_b34@180043ee...; fixed length/quality eligibility engineering choices, not universal RTKLIB quality. V0/V0E/V1/V2 are config conditions not four independent papers'),
 'LC01':('Pavlasek et al. two-position-receiver IEKF','Two HPPOSECEF+pAcc positions +Go2 body IMU, no RV/RD/SDK weak priors','First valid p2-p1 initializes yaw; gyro/acc body adapter; LIT noise','bias-free SE2(3) R/v/p nine-state','own estimated attitude; two-position correlated measurement','Native IMU/body origin ->declared midpoint in v3 offline contract','Natural LIT H.097548/.074606/.054304m; yaw2.994827/2.208612/2.453697deg (H contract start); H all4 LIT/S starts geomFAIL retained','Main paper IEKF implemented; appendix MEKF absent. Own initialization/process covariance and scalar R=pAcc^2 differ LegSA. Post-result LIT choice disclosed; not same-input solver ranking'),
 'LC01-S':('Pavlasek IEKF with project-calibrated IMU parameters','Same two HP positions, accelerometer*s and BY2 effective noise','Same dual-receiver initialization; BY2 calibration shared within campaign','Same9state IEKF','own estimated attitude','same declared midpoint offline; not independent reference POI proof','S supplementary; yaw1.539239/1.943003/4.015602deg; H geomFAIL','A parameter condition of LC01, not another paper; BY2 calibration development overlap disclosed'),
 'EXT05C':('Single-receiver-update IEKF diagnostic (dual-receiver initialization)','GNSS1 HP position/pAcc +Go2 IMU; no RV/RD/SDK priors','GNSS2 baseline used once for initial yaw, then p1-only','same9state IEKF with p1-only update','own attitude propagated/lever coupled; no direct online dual yaw','native IMU origin ->declared midpoint in v3','yaw12.048642/20.108223/5.845502deg (H contractstart); H FILE_START55.609934deg also kept','Not pure one-antenna information from initialization, not an independently claimed author method'),
 'EXT05C-S':('Single-receiver-update IEKF with project IMU parameters','EXT05C plus S scaling/noise','dual-receiver yaw init; S development overlap','same9state IEKF','own estimated attitude','declared midpoint','H FILE_START true divergence preserved; H contractstartyaw8.114756deg, BY2/O9.722098/8.266805deg','Supplementary project configuration; no result cherry-pick across starts'),
 'LC02_GINAV':('Official GINav SPP/INS loosely coupled route','GNSS1RAWX/SFRBX->RINEX->SPP +Go2 IMU','Official TDCP velocity alignment; no GNSS2/A1 or SDK attitude','official GNSS/INS LC states','INS attitude; position/velocity SPP updates','IMU point under official convention, old vs newer offline contracts distinguish','Actual3seq native; oldBY2 77/275 H130.818726/3D219.883711m,yaw69.753332deg; HX02 B/O D8fail,H2/271','Official@bc6b3ab6... mathematical functions unchanged, adaptation/options declared. 2/2 own coverage does not mean full271slots; no new row from unavailable B/O'),
 'Hartley':('Official contact-aided InEKF with Go2 kinematic proxy','Go2 IMU +foot_position_body high-level FK proxy +force hysteresis; no GNSS/joint encoder','project1s initialization; yaw0 arbitrary gauge; OFF-LIT/OFF-DEF','R/v/p/bias/contact state','own relative attitude, xyz/yaw4DOF unobservable','relative pose after one first10s xyz+yaw gauge alignment; not absolute POI','Official OFF-LIT aligned H50.187/68.545/77.504m,yaw62.173/77.485/90.896deg; all6 official runs complete','Official core unmodified@ef16e8a...; observation proxy/noise/force/axis adapter are project engineering. Not original joint/contact measurement experiment, cannot absolute-rank with GNSS')}
inv=[]
for r in old:
 m=r['method_id'];u=updates.get(m)
 if u is None:u=(m,r['estimated_state_and_inputs'],'NOT_EXECUTED_OR_NOT_ADMITTED',r['estimated_state_and_inputs'],'NO_VALID_PERFORMANCE_QUANTITY','NOT_APPLICABLE_NO_VALID_RESULT',r['current_status'],r['forbidden_claims'])
 inv.append({'internal_identity':m,'reader_name':u[0],'original_registry_member':True,'method_level':r['audit_level'],'paper_identity_from_registered_sources':r['reference'],'input_layer':u[1],'initialization_information':u[2],'estimated_state':u[3],'attitude_quantity':u[4],'position_quantity_and_POI':u[5],'actual_result_scope':u[6],'author_algorithm_vs_project_boundary':u[7],'historical_20261003_status':r['current_status'],'frozen_original_V3_relationship':'External method/condition; does not alter original6468 LegSA-GINS matrix. Historical ORIGINAL_V3_MAIN placeholders apply original report time.','source_mapping':r['paper_to_function'],'existing_asset_roots_or_evidence':r['audit_evidence'],'scientific_replay_this_block':False})
for variant,desc,results in [('V0E','V0config with mixed BRDC nav','194/217/231; yaw20.646991/31.263814/20.402911deg'),('V1','V0E plus navsys57','154/186/117; yaw14.611254/12.732971/21.781901deg'),('V2','V1 plus fix-and-hold','60/149/93; yaw4.511761/10.622992/19.205502deg')]:
 base=dict(next(r for r in inv if r['internal_identity']=='RTKLIB_UNMODIFIED_MOVING_BASE'));base.update(internal_identity='RTKLIB_'+variant,reader_name='RTKLIB moving-base ('+variant+' condition)',original_registry_member=False,input_layer=desc+'; same complete HX02 observation history, noIMU',actual_result_scope=results,source_mapping='HX07R_REPORT + original COMMAND/config/EVAL identities',existing_asset_roots_or_evidence='/mnt/g/LegSA-GINS-project/clean_rebuild_202607/stages/CLEAN9_EXTERNAL_COMPARISON/HX07R/RUNS/');inv.append(base)
fgos=[('OISAM','OiSAM selected INS/GNSS branch','RTK GNSS1 position +body IMU; one A1 gauge per initialization','15-state INS, bias, Earth preintegration, structured Givens/cache,30/40 A-JSWR,Ceres','own estimated attitude; GNSS1 via own Cbn/lever in newdiag','Strict oneA1 no-reset: B275/H0/O55. Segmented3new with1/3/7 predeclared gap blocks; primary275/267/370,secondary275/269/376. W/GNC6reuse.','Author Oi executable unavailable; OB_GINS Earth bridge actual compiled. Per-block A1 adds information and changes protocol; no within-block outcome reset; no whole author experiment replay.'),('WEN_TC','Wen et al. raw-pseudorange/AHRS factor graph','raw code +Go2 manufacturer quaternion/AHRS/linear acceleration; one initial A1 AHRS gauge','batch p/v/ba/clock with right-end AHRS/acceleration motion link','No self-estimated attitude; GNSS1 antenna position','274/270/377 full-batch support; segmented diagnostic reuses exact original native6overall','External AHRS/manufacturer Go2 vs author XSens Ti10 dynamics/calibration/latency not proved equivalent; selected TC model core, not all paper alternatives.'),('GNC','GNC GNSS factor graph (GM/Eq21 selected branch)','raw code +Doppler velocity-derived links; noRTK/AHRS/legs','position/clock graph +GM state/weight alternation','No self-estimated attitude; GNSS1 antenna','274/270/377; batch reused in newdiag, not six new native','Eq21 squared main vsEq22 ambiguity not resolved by author code; native stopping/order recorded, exact author inputs/noise/init all unavailable.')]
for m,name,inputs,state,qty,result,bound in fgos:
 inv.append({'internal_identity':m,'reader_name':name,'original_registry_member':False,'method_level':'selected complete estimation chain independent implementation with declared engineering instantiation','paper_identity_from_registered_sources':'docs/paper_rebuild/FGO_COMPLETE_AUDIT_20261004/AUTHOR_MATERIALS.md','input_layer':inputs,'initialization_information':inputs.split(';')[-1] if m=='OISAM' else 'Paper-selected initialization, no offline reference; exact native ledger','estimated_state':state,'attitude_quantity':qty,'position_quantity_and_POI':'Strict Oi midpoint vs W/GNC GNSS1 kept separate; newdiag allGNSS1 samepoint, no old row overwritten','actual_result_scope':result,'author_algorithm_vs_project_boundary':bound,'historical_20261003_status':'prior FGO14 runs preserved separately; strict20261004 distinct generation','frozen_original_V3_relationship':'Comparison/sensitivity only, no originalV3 native rerun','source_mapping':'COMPLIANCE_MATRIX.csv45rows and frozen22source overlay/native seals; newdiag872source snapshot scope distinct','existing_asset_roots_or_evidence':'Strict /home/kaiwen/research/LegSA-GINS-SCRATCH/FGO_REPRODUCTION_FIX_20261004/FGO_REPRODUCTION_FINAL_20261004T054410Z; newdiag '+str(SG),'scientific_replay_this_block':False})
inv.append({'internal_identity':'LEG_DR','reader_name':'Go2 SDK-attitude dead-reckoning input diagnostic','original_registry_member':False,'method_level':'conditional input diagnostic','paper_identity_from_registered_sources':'HX02E/HX05 diagnostic, no independent author paper','input_layer':'SDKbody velocity +manufacturer attitude','initialization_information':'project alignment/gauge','estimated_state':'integrated trajectory with supplied attitude','attitude_quantity':'supplied SDK attitude, not independently estimated','position_quantity_and_POI':'relative aligned diagnostic, no GNSSabsolute anchor','actual_result_scope':'H6.209/9.178/6.322m aligned; retained diagnostic','author_algorithm_vs_project_boundary':'Cannot establish official InEKF mathematics is wrong or replacement algorithm superiority','historical_20261003_status':'retained conditional diagnostic','frozen_original_V3_relationship':'not part6468','source_mapping':'HX02E_HARTLEY_OFFICIAL/90_AGGREGATE, HX05supp','existing_asset_roots_or_evidence':'/mnt/g/LegSA-GINS-project/clean_rebuild_202607/stages/CLEAN9_EXTERNAL_COMPARISON/HX02E_HARTLEY_OFFICIAL','scientific_replay_this_block':False})
assert len(inv)==30 and len({r['internal_identity'] for r in inv})==30
wc('EXTERNAL_METHOD_STORY.csv',inv)
# Separate weight-shape analogues have no complete factor-system identity.
analog=[{'internal_family':m,'reader_scope':'internal covariance-inflation shape diagnostic','state_or_objective':'OIM scalar R multiplier only','formal_LegSA_GINS_used':False,'author_complete_algorithm_reproduction':False,'source_frozen_path':'cpp/legsa_v23_port_core/src/source_aware/source_aware_policy.cpp','frozen_revision':'7d43b9af26120ed5dde21f53e515386361072ba6','source_lines':'437-552','boundary':'No original author factor state, optimization, switch variable or complete estimator. Formal clean_v1_conservative branch separately mapped; no independent-paper performance count.'} for m in ['Huber','Cauchy','Tukey','IGG3','Barron','DCS','switchable analogue']];wc('INTERNAL_ROBUST_ANALOGUE_SCOPE.csv',analog)
# Compact numeric lookup retains original decimal strings and support roles, not comparable normalized scores.
lookup=[]
for r in ext:lookup.append({'generation':'EXT_V2_TECH_RETRY_2_or_explicit_reused_RTKLIB','sequence_id':r['sequence_id'],'internal_method_id':r['method_id'],'support_role':r['support'],'status':r['status'],'expected_denominator':r['paired_epoch_denominator'],'matched_count':r['scored_count'],'H_RMSE_m':'','V_RMSE_m':'','3D_RMSE_m':'','heading_RMSE_deg':r['rmse_deg'],'physical_quantity':r['reported_quantity']+' vs '+r['reference_quantity'],'exact_source_copy':'COMPARISON_SOURCES/EXT_V2_COMPARISON_TABLE.csv','source_row_key':r['source_row_key']})
for generation,rr in [('FGO_STRICT_20261004',fgo),('FGO_SEGMENTED_DIAGNOSTIC_20261004',seg)]:
 for r in rr:lookup.append({'generation':generation,'sequence_id':r['sequence_id'],'internal_method_id':r['method_id'],'support_role':r.get('support_role','STRICT_SELECTED_SUPPORT')+' /'+r['support'],'status':r['status'],'expected_denominator':r['expected_epoch_count'],'matched_count':r['matched_epoch_count'],'H_RMSE_m':r['horizontal_rmse_m'],'V_RMSE_m':r['vertical_rmse_m'],'3D_RMSE_m':r['position_3d_rmse_m'],'heading_RMSE_deg':r['yaw_rmse_deg'],'physical_quantity':r['physical_point']+' /own attitude only if estimated','exact_source_copy':'COMPARISON_SOURCES/'+('FGO_STRICT_METRICS.csv' if generation.startswith('FGO_STRICT') else 'FGO_SEGMENTED_'+r['sequence_id']+'_METRICS.csv'),'source_row_key':r.get('support_role','')+'/'+r['method_id']+'/'+r['support']})
wc('FROZEN_EXTERNAL_METRICS_OVERVIEW.csv',lookup);assert len(lookup)==126
for r in sources:r['sha256_after']=sha(r['actual_path']);assert r['sha256_after']==r['sha256_before']
wc('COMPARISON_SOURCE_ASSET_INDEX.csv',sources);assert all(sha(B/n)==h for n,h in before.items())
d={'schema':'v3_story.fourth_block.data.v1','created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'all_checks_passed':True,'prior56_unchanged':True,'prior56_before_pins':before,'prior56_after_pins':{n:sha(B/n) for n in before},'sources':sources,'copied_files':copied,'registry_rows':23,'reader_identity_rows':30,'robust_analogue_rows':7,'numeric_lookup_rows':len(lookup),'new_segmented_rows':36,'new_segmented_native_count':3,'new_segmented_reused_native_count':6,'science_calls_this_block':{'native':0,'evaluator':0,'raw_or_trace_payload_read':0,'provider_generator':0,'parameter_change':0},'helper_sha256':sha(__file__),'limitation':'Machine full field read and identity copy; human semantic ranges separately recorded. No method equivalence inferred from poor outcomes. No new metric calculation or scientific pipeline import.'}
p=B/'FOURTH_BLOCK_DATA_RECEIPT.json';assert not p.exists();p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');p=B/'build_fourth_story_block.py';assert not p.exists();p.write_bytes(Path(__file__).read_bytes());print('FOURTH_DATA_READY',len(sources),'sourceassets',len(copied),'copies',len(inv),'readeridentities',len(lookup),'numericrows')
