from pathlib import Path
import csv,collections,gzip,hashlib,json,datetime,re,subprocess
C=Path('/home/kaiwen/research/LegSA-GINS-WORKTREES/audit-code-xbpg-20261001');B=C/'docs/paper_rebuild/V3_STORY_20261004';X=Path('/mnt/g/LegSA-GINS-project/修复_20261004/V3_STORY_SOURCE_READ_02');F='7d43b9af26120ed5dde21f53e515386361072ba6'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'),allow_nan=False)
def write_csv(name,rows):
 rows=list(rows);assert rows;target=B/name;assert not target.exists(),target
 with target.open('x',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 return len(rows)
def write_json(name,d):
 p=B/name;assert not p.exists();p.write_text(json.dumps(d,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
first=json.loads((B/'FIRST_BLOCK_READY_RECEIPT.json').read_text());print('ready keys',list(first),flush=True)
first_before={p.name:sha(p) for p in B.iterdir() if p.is_file() and p.name not in ['TASK_LEDGER.csv','METRIC_LEDGER.csv','NATIVE_ACTION_LEDGER.csv']}
assert len(first_before)==18
with gzip.open(B/'TASK_LEDGER.csv.gz','rt') as f:tasks=list(csv.DictReader(f))
with gzip.open(B/'METRIC_LEDGER.csv.gz','rt') as f:metrics=list(csv.DictReader(f))
models=json.loads((B/'CONFIG_MODEL_FACTORS.json').read_text())
names={r['internal_method_id']:r for r in csv.DictReader((B/'METHOD_READER_NAME_MAP.csv').open())}
context=collections.defaultdict(list)
for r in tasks:context[r['sequence_id'],r['internal_method_id']].append(r)
assert len(context)==33
ctx=[];diff=[]
for (s,m),rr in sorted(context.items()):
 ids={r['config_model_id'] for r in rr};assert len(ids)==1;mid=ids.pop();v=models[mid]['values'];base=next(r for r in context[s,'F04'])['config_model_id'];bv=models[base]['values'];changes={k:{'full':bv.get(k),'candidate':v.get(k)} for k in sorted(set(bv)|set(v)) if bv.get(k)!=v.get(k)}
 for r in rr:assert r['config_model_id']==mid
 ctx.append({'sequence_id':s,'paper_reader_name':names[m]['paper_reader_name'],'internal_method_id':m,'config_model_id':mid,'physical_task_count':len(rr),'completed':sum(r['native_status']=='COMPLETED' for r in rr),'diverged':sum(r['native_status']=='ALGORITHM_FAILURE_DIVERGED' for r in rr),'no_valid_heading':sum(r['native_status']=='ALGORITHM_FAILURE_NO_VALID_HEADING_INPUT' for r in rr),'window_s_json':canon([v['starttime'],v['endtime']]),'initial_position_deg_deg_m_json':canon(v['initpos']),'initial_rpy_deg_json':canon(v['initatt']),'common_dual_heading_initialization':v['common_initialization_dual_yaw_used'],'arw_deg_per_sqrt_hour_json':canon(v['arw']),'vrw_mps_per_sqrt_hour_json':canon(v['vrw']),'gbstd_deg_per_hour_json':canon(v['gbstd']),'abstd_mgal_json':canon(v['abstd']),'correlation_time_hour':v['corrtime'],'antlever_frd_m_json':canon(v['antlever']),'active_feature_flags_json':canon({k:v[k] for k in ['enable_dual_yaw','enable_receiver_velocity','enable_raw_doppler','enable_source_aware','enable_go2_roll_pitch_prior','enable_go2_horizontal_velocity_prior']}),'original_transport_runtime_role':v.get('runtime_role'),'source_config_path':models[mid]['source_config_path'],'config_model_sha256':models[mid]['sha256']})
 if m!='F04':diff.append({'sequence_id':s,'full_internal_id':'F04','candidate_internal_id':m,'candidate_reader_name':names[m]['paper_reader_name'],'changed_fields_json':canon(changes),'single_feature_switch_only':m in ['A03','A04','A05','A06'],'note':'algorithm_id/ablation_variant are bookkeeping identities; F01 has inactive basic-yaw std difference, H/O F01 runtime role differs; source/provider identity is per task ledger'})
assert all(set(json.loads(x['changed_fields_json']))=={'algorithm_id','ablation_variant',{'A03':'enable_raw_doppler','A04':'enable_source_aware','A05':'enable_go2_roll_pitch_prior','A06':'enable_go2_horizontal_velocity_prior'}[x['candidate_internal_id']]} for x in diff if x['single_feature_switch_only'])
counts={}
counts['CONFIG_CONTEXT_STORY.csv']=write_csv('CONFIG_CONTEXT_STORY.csv',ctx)
counts['CONFIG_COMPARISON_DIFFS.csv']=write_csv('CONFIG_COMPARISON_DIFFS.csv',diff)
fields=['run_id','paper_reader_name','internal_method_id','sequence_id','domain','case_id','data_mode','evaluator_contract','evaluation_status','matched_epoch_count','output_epoch_count','coverage_ratio','horizontal_rmse_m','up_rmse_m','position_3d_rmse_m','roll_rmse_deg','pitch_rmse_deg','yaw_rmse_deg','horizontal_p95_m','yaw_p95_absolute_deg','horizontal_max_m','yaw_max_absolute_deg','registered_table_path','registered_table_line','native_nav_sha256','evaluator_nav_sha256','trace_sha256']
natural=[{k:r[k] for k in fields} for r in metrics if r['data_mode']=='real_clean'];assert len(natural)==66 and len({(r['sequence_id'],r['internal_method_id'],r['evaluator_contract']) for r in natural})==66
counts['NATURAL_METHOD_RESULTS.csv']=write_csv('NATURAL_METHOD_RESULTS.csv',sorted(natural,key=lambda x:(x['evaluator_contract'],x['sequence_id'],x['internal_method_id'])))
metric_fields=[k for k in metrics[0] if k.startswith(('north_','east_','up_','roll_','pitch_','yaw_','horizontal_','position_3d_'))];assert len(metric_fields)==128
stats={'signed_mean':'arithmetic signed mean','bias':'same value as signed_mean','signed_median':'median signed component error','standard_deviation':'population std, ddof=0','rmse':'sqrt(mean(e^2)); sample weighted','mae':'mean(abs(e))','median_absolute_error':'median(abs(e))','p50_absolute':'percentile(abs(e),50)','p75_absolute':'percentile(abs(e),75)','p90_absolute':'percentile(abs(e),90)','p95_absolute':'percentile(abs(e),95)','p99_absolute':'percentile(abs(e),99)','max_absolute':'max(abs(e))','final_signed_error':'last matched signed error','final_absolute_error':'absolute error at last matched epoch','iae':'trapezoidal integral of abs(e) over matched times','ise':'trapezoidal integral of e^2 over matched times','mean':'mean(nonnegative norm)','median':'median(nonnegative norm)','p50':'percentile(norm,50)','p75':'percentile(norm,75)','p90':'percentile(norm,90)','p95':'percentile(norm,95)','p99':'percentile(norm,99)','max':'max norm','final':'last matched norm'}
dic=[]
for k in metric_fields:
 prefix=next(p for p in ['position_3d','horizontal','north','east','up','roll','pitch','yaw'] if k.startswith(p+'_'));unit='deg' if prefix in ['roll','pitch','yaw'] else 'm';stat=k[len(prefix)+1:-(len(unit)+1)];phys=unit+' s' if stat=='iae' else unit+'^2 s' if stat=='ise' else unit
 dic.append({'original_field_name':k,'quantity':prefix,'statistic':stat,'definition':stats[stat],'physical_unit':phys,'original_name_unit_suffix':unit,'support':'finite matched evaluator epochs inside fixed window; caller rejects nonfinite evaluated errors','error_sign_or_norm':'estimate minus reference; wrapped [-180,180) for attitude' if prefix not in ['horizontal','position_3d'] else 'nonnegative Euclidean norm','source_revision':F,'source_functions':'clean5_parity_p04/evaluation.py:18-27 -> canonical541/offline_eval_aggregate.py:259-330'})
counts['METRIC_QUANTITY_DICTIONARY.csv']=write_csv('METRIC_QUANTITY_DICTIONARY.csv',dic)
prior=json.loads((X/'PRIOR_CPP_READ_IDENTITY.json').read_text());assert len(prior)==33 and all(r['same_blob'] for r in prior)
write_json('ORIGINAL_CPP_INHERITED_READ_IDENTITY.json',{'original_science_freeze':F,'prior_full_read_evidence':'/mnt/g/LegSA-GINS-project/审查_20261003/active_core_read_coverage.csv','prior_evidence_sha256':sha('/mnt/g/LegSA-GINS-project/审查_20261003/active_core_read_coverage.csv'),'full_same_blob_count':32,'partial_same_blob_count':1,'machine_identity_comparison_only':True,'new_semantic_read_ranges_separately_recorded':True,'files':prior})
source_rows=[]
def source(role,path,start,end,purpose,scope,limits):
 b=subprocess.check_output(['git','-C',str(C),'show',F+':'+path]);source_rows.append({'method_component':role,'source_path':path,'frozen_revision':F,'sha256':hashlib.sha256(b).hexdigest(),'line_start':start,'line_end':end,'purpose':purpose,'paper_scope':scope,'boundary':limits})
source('error state','cpp/legsa_v23_port_core/include/legsa_v23_port_core/types.hpp',40,60,'21 slots: dp,dv,phi,bg,ba,sg,sa','15 active + 6 scale slots frozen at zero in all original matrix configs','No online full IMU scale calibration claim')
source('inertial propagation','cpp/legsa_v23_port_core/src/kf_gins/insmech.cpp',18,77,'velocity -> position -> attitude; two-sample coning/sculling; Earth rotation/transport/gravity','Source-backed GNSS/INS backbone','Backbone is inherited engineering implementation, not claimed novelty')
source('prediction and feedback','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',442,545,'Phi P Phi^T+Q; Joseph update; error feedback and aligned IMU split','Closed-loop error-state EKF','Use actual implemented F/G/Phi/Qd, not an unverified full textbook model')
source('error dynamics','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',786,851,'Qc, implemented F/G blocks; Phi=I+Fdt and symmetric Q discretization','Original frozen propagation model','Effective process parameters are project priors, not independent truth calibration')
source('position/RV','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',853,954,'GNSS1 antenna position and lever velocity residuals','Distinct position and receiver-velocity measurements','Same receiver position/velocity/RD correlation not modeled as independent truth')
source('scalar heading','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',956,1019,'wrapped scalar residual; scheme-C hard/soft gate; H_phi_z=-1; Basic ungated fixed sigma path','A1 baseline-derived scalar heading','Original small-tilt scalar model; no baseline3D factor in original matrix')
source('Raw Doppler','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',1151,1233,'nearest provider within tolerance; lineage/satellite gate; antenna velocity residual','Auxiliary velocity derived from RAWX plus satellite-state backend','Native factor consumes velocity product, not per-satellite tightly coupled raw residual')
source('Go2 RP','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',1235,1290,'nearest supported Go2 roll/pitch weak prior','2D attitude weak prior, configurable std 1.6 deg','No Go2 truth/contact/forward-kinematics claim')
source('Go2 HV','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',1292,1370,'nearest update_flag provider; horizontal 2D velocity prior','SDK body velocity -> historical navigation-frame weak prior','Inherited HV uses A1-derived rotation; V3 did not regenerate it')
source('source-aware interface','cpp/legsa_v23_port_core/src/kf_gins/gi_engine.cpp',1617,1686,'NIS via S=HPH^T+R, source metadata and capped R inflation','LSIM+OIM for six observation-source classes','Rolling baseline is diagnostic; QA/QM disabled')
source('source-aware policy','cpp/legsa_v23_port_core/src/source_aware/source_aware_policy.cpp',154,436,'source cap, metadata quality and conservative LSIM','Source-dependent conservative covariance inflation','metadata contact/readiness is not a contact kinematic factor')
source('source-aware OIM','cpp/legsa_v23_port_core/src/source_aware/source_aware_policy.cpp',554,694,'deadband 1.5, source alpha, moderate/strong multiplier; max(LSIM,OIM)','clean_v1_conservative_quadratic branch','QA11E named robust shapes elsewhere are analogues, not author full estimators')
source('configured native loop','cpp/legsa_v23_port_core/src/runtime/port_runtime.cpp',1320,1580,'preflight inputs, fixed initialization, one pending GNSS epoch and same-run NAV/STD','Actual original online dispatch','Auxiliary RP/HV/RD dispatched at valid GNSS events; full GNSS dropout blocks all such updates')
source('GNSS18 loader','cpp/legsa_v23_port_core/src/fileio/gnss_file_loader.cpp',116,194,'LLH, std, RV, yaw with three independent valid flags','18-column formal measurement identity','No separate baseline3D path activated')
source('configuration units','cpp/legsa_v23_port_core/src/config/port_config_loader.cpp',572,607,'deg->rad; deg/h->rad/s; mGal->m/s2; ppm->fraction; hours->seconds','Exact physical units used by original models','Flat line parser requires frozen inline representations')
source('task registration','src/legsa_gins/paper_rebuild/protocol_v3/registry.py',91,203,'old frozen config/providers and complete 6468 task cohort','Whole-matrix history and aliases','Expected donor echo is identified witness, never an emitted echo for failed native')
source('R5 provider','src/legsa_gins/paper_rebuild/protocol_v3/providers.py',118,303,'same iTOW raw heading and frozen fault lift; only yaw13/valid17 byte changes','Explicit input-layer evolution from V2 base','No independent random 5Hz redraw; std/HV unchanged')
source('raw-heading construction','src/legsa_gins/paper_rebuild/hext/t5a_provider.py',49,316,'frozen A1 conversion of exact paired HP positions; both PVT carrSoln=2','R5 heading identity','Zero accuracy adapter placeholders are not measured noise; both-fixed is not installation calibration')
source('native/evaluator isolation','src/legsa_gins/paper_rebuild/protocol_v3/runtime.py',119,284,'consumed no-retry native/eval slots; native access audit then sealed evaluator child','Zero online reference and failure-preserving reporting','Evaluation v2/v3 use one same native trajectory; no substitute outputs')
source('declared POI transform','src/legsa_gins/paper_rebuild/clean5_parity/evaluation.py',25,85,'Cbn times [0.03,0.03-baseline/2,-0.30] then WGS84 ECEF','v3 declared physical point contract','Lever and reference POI are declared engineering geometry; covariance untransported')
source('128 scalar metrics','src/legsa_gins/paper_rebuild/canonical541/offline_eval_aggregate.py',259,330,'six signed axes x17 plus two norms x13; trapezoidal integrals','Exact statistic interpretation','IAE/ISE physical units include seconds despite original field suffix')
counts['METHOD_SOURCE_MAP.csv']=write_csv('METHOD_SOURCE_MAP.csv',source_rows)
write_json('SECOND_BLOCK_DATA_RECEIPT.json',{'schema':'v3_story.second_block.v1','all_checks_passed':True,'captured_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_science_freeze':F,'first_block_commit':'baf4e9157c7b82d611271f15ae9b7e68f3014ab3','first_block_before_pins':first_before,'first_block_after_pins':{n:sha(B/n) for n in first_before},'first_block_unchanged':all(sha(B/n)==h for n,h in first_before.items()),'input_rows':{'tasks':len(tasks),'metrics':len(metrics),'unique_nontransport_models':len(models)},'output_data_rows':counts,'four_single_switch_pair_checks':12,'old_cpp_0625_same_blob_checks':33,'science_calls':{'native':0,'evaluator':0,'provider_generator':0,'raw_or_trace_payload_reads':0},'reader_helper_sha256':sha(__file__),'files':{n:sha(B/n) for n in [*counts,'ORIGINAL_CPP_INHERITED_READ_IDENTITY.json']},'limitation':'Structured task/config/metric traversal is machine reading. Original C++ inherited full semantic coverage is same-blob verified; selected new reads are registered separately. No matrix validation rerun or new scientific result.'})
print('SECOND_DATA_BLOCK_PASS',counts,flush=True)
