#!/usr/bin/env python3
"""DG01 summary, source receipts and report; no scientific runtime calls."""
from dg01_analysis import *
import shutil,subprocess
def overview():
 quality=pd.read_csv(R/'DG01_SIGNAL_QUALITY.csv');out=[]
 for s in SEQ:
  for r in [1,2]:
   a=inside(load(s,r,'obs'),s);n=inside(load(s,r,'nav'),s);q=quality[(quality.sequence==s)&(quality.receiver==r)];rel=inside(load(s,r,'rel'),s)
   out.append(dict(sequence=s,receiver=r,raw_epochs=a.time.nunique(),raw_signal_rows=len(a),cno_median=a.cno_dbhz.median(),cno_p05=a.cno_dbhz.quantile(.05),cno_p95=a.cno_dbhz.quantile(.95),NAV_epochs=len(n),fixed_count=int(n.carrSoln.eq(2).sum()),hAcc_median=n.hAcc_m.median(),lock_resets=int(q[q.metric=='lock_reset'].event_count.sum()),cp_overflow=int(q[q.metric=='cp_overflow'].event_count.sum()),RINEX_LLI0=int(q[q.metric=='LLI_bit0'].event_count.sum()),RELPOS_median_m=rel.length_m.median(),RELPOS_heading_valid=int(rel.heading_valid.sum()),RELPOS_refids=';'.join(map(str,sorted(rel.ref_station.unique()))),source=f'{s}_R{r}_obs/nav/rel.csv.gz;DG01_SIGNAL_QUALITY.csv'))
 write('DG01_OVERVIEW.csv',out,True)
 cm=pd.read_csv(R/'DG01_CMC.csv');rows=[]
 for key,g in cm.groupby(['sequence','receiver','proxy','segment']):rows.append(dict(zip(['sequence','receiver','proxy','segment'],key),n_cells=len(g),n_finite_sd=int(g['std'].notna().sum()),median_sd_m=g['std'].median(),p95_sd_m=g['std'].quantile(.95),source='DG01_CMC.csv'))
 write('DG01_CMC_OVERVIEW.csv',rows,True)
 stab=[]
 for s in SEQ:
  d=pd.read_csv(O/f'{s}_FRACTIONAL_STABILITY.csv.gz')
  for key,g in d.groupby(['gnss','signal','fix_group']):stab.append(dict(sequence=s,gnss=key[0],signal=key[1],fix_group=key[2],n_identity_time_cells=len(g),median_circular_sd=g.circular_sd.median(),p95_circular_sd=g.circular_sd.quantile(.95),source=f'{s}_FRACTIONAL_STABILITY.csv.gz'))
 write('DG01_DD_STABILITY_SUMMARY.csv',stab,True)
def boundary():
 out=[]
 for s in SEQ:
  p=read(run_dir(s,'RTKLIB')/'native/HX02_HEADING_TABLES/HX02_HEADING_TABLE_RTKLIB.csv');n=pd.read_csv(p);n['native_time']=n.time_unix_s-SEQ[s][0];n['grid']=np.rint(n.gps_tow_seconds/.2).astype(int)
  d=pd.read_csv(O/f'{s}_RTKLIB_POS_DETAIL.csv.gz');d['grid']=np.rint((d.time+SEQ[s][0]+18-315964800-2408*604800)/.2).astype(int);j=d.merge(n[['grid','native_time','valid','rtklib_q']],on='grid',how='left');j['sequence']=s;j['native_in_window']=j.native_time.between(SEQ[s][1],SEQ[s][2]);j['pos_minus_native_s']=j.time-j.native_time
  write(f'{s}_RTKLIB_TAG_ASSOCIATION.csv.gz',j);out+=j[(j.Q==1)&(~j.native_in_window|j.valid.ne(1))].to_dict('records')
 write('DG01_RTKLIB_BOUNDARY_ROWS.csv',out,True)
def validate():
 checks=[]
 for s in SEQ:
  for r in [1,2]:
   d=pd.read_csv(O/f'{s}_R{r}_CMC_DETAIL.csv.gz');a=d[d.proxy=='dual_frequency_MP'];keys=['gnss','sv','signal','frequency_id','arc','second_signal','second_arc','proxy'];n=a.groupby(keys).time.transform('size');checks.append(dict(check=f'{s}_R{r}_single_epoch_arc_is_unavailable',passed=bool(a.loc[n<2,'residual_m'].isna().all())))
  d=pd.read_csv(O/f'{s}_FRACTIONAL_DD_DETAIL.csv.gz');checks.append(dict(check=s+'_DD_wrap_range',passed=bool(((d.fractional_cycles>-.5)&(d.fractional_cycles<=.5)).all())))
  j=pd.read_csv(O/f'{s}_FIX_DETAIL.csv.gz');checks.append(dict(check=s+'_fix_states_partition',passed=bool(((j.both_fixed.astype(int)+j.one_fixed.astype(int)+j.neither_fixed.astype(int))==1).all())))
 pins=json.loads((O/'DG01_RAW_PINS.json').read_text())
 for p in pins:checks.append(dict(check=p['sequence']+'_R'+str(p['receiver'])+'_'+p['stream']+'_sha256',passed=sha(p['path'])==p['expected']))
 assert all(x['passed'] for x in checks),checks
 (R/'DG01_CHECKS.json').write_text(json.dumps(checks,indent=2)+'\n')
 return checks
def table(df,cols=None):
 if cols is not None:df=df[cols]
 def f(v):
  if pd.isna(v):return 'UNAVAILABLE'
  if isinstance(v,(float,np.floating)):return str(int(v)) if float(v).is_integer() else f'{v:.3f}'
  return str(v).replace('|','\\|')
 return '| '+' | '.join(df.columns)+' |\n| '+' | '.join('---' for _ in df.columns)+' |\n'+'\n'.join('| '+' | '.join(f(v) for v in row)+' |' for row in df.itertuples(index=False,name=None))
def report(checks):
 overview_df=pd.read_csv(R/'DG01_OVERVIEW.csv');fix=pd.read_csv(R/'DG01_FIX_STATUS_TIMELINE.csv');dd=pd.read_csv(R/'DG01_FRACTIONAL_DD.csv');cm=pd.read_csv(R/'DG01_CMC_OVERVIEW.csv');inter=pd.read_csv(R/'DG01_INTER_RECEIVER.csv');motion=pd.read_csv(R/'DG01_VALIDITY_MOTION.csv');q=pd.read_csv(R/'DG01_RTKLIB_Q_OVERLAP.csv');audit=pd.read_csv(R/'DG01_RTKLIB_CONFIG_AUDIT.csv');stability=pd.read_csv(R/'DG01_DD_STABILITY_SUMMARY.csv');pins=json.loads((O/'DG01_RAW_PINS.json').read_text());inv=pd.read_csv(R/'DG01_MESSAGE_INVENTORY.csv');qa=json.loads((R/'DG01_FIGURE_QA.json').read_text());start=json.loads((O/'DG01_PREFLIGHT.json').read_text())['started'];elapsed=(datetime.datetime.now(datetime.timezone.utc)-datetime.datetime.fromisoformat(start)).total_seconds()/60
 blocks=['# DG-01 原始 GNSS 观测诊断与 RTKLIB 配置审计','', '状态：诊断及交付检查完成；仅陈述观测事实，不作方法适用性裁决。登记提交 `ceb00f2925ddd9e721fd05fe91392a9bf080e3a0`；结果提交为本文件所属提交，最终回贴给出确切哈希与 push 回执。','', '## 0. 边界、输入与分母','', 'LegSA 解算/评估、provider、外部原生、RTKLIB 重跑均为 0；参考原始轨迹读取 0。三序列现有 RINEX 齐全，未重建、未调用 bridge。所有数据读取经过原始哈希或输入清单登记；没有读取 trace/.bag/.fpl 文件。G: 只写 DG01 目录。原始文件开始和结束核验 12/12；既有未跟踪 29/29 保持原样，提交前后另作 Git 复核。','', 'HX02 实际根为 `<CLEAN_ROOT>/stages/CLEAN9_EXTERNAL_COMPARISON/HX02_FIVE_CATEGORY`。时窗及 base_time 见 DG01_REGISTRATION.md：BY2 [66,340]、BY2H [413,683]、BY2O [3186,3563] s。这里 NAV 的闭窗与 RAWX 的小数时标不强行改成同一历元分母。源文件别名由本地 DATA_PATHS 配置解析；逐文件 SHA256 见 DG01_INPUT_SHA256.json。','', '## D1. 消息与 NAV-RELPOSNED 身份','', '原始流消息逐类型数量/速率，以及 status 每个字段的非空数量均在 DG01_MESSAGE_INVENTORY.csv（sequence、receiver、stream、message_or_field 唯一定位）。以下为主要 UBX 消息窗口计数；完整清单保留其他 UBX/NMEA 消息。']
 kinds=['UBX-RXM-RAWX','UBX-RXM-SFRBX','UBX-NAV-PVT','UBX-NAV-SAT','UBX-NAV-SIG','UBX-NAV-RELPOSNED'];small=inv[(inv.stream=='raw')&inv.message_or_field.isin(kinds)].pivot(index=['sequence','receiver'],columns='message_or_field',values='count_window').reset_index();blocks+=['',table(small),'',f'UBX 长度/checksum 失败帧共 {int(inv.bad_checksum_or_length.sum())}，出处同清单该列求和。字段解码遵循 [u-blox ZED-F9T 接口说明](https://content.u-blox.com/sites/default/files/ZED-F9T_InterfaceDescription_%28UBX-18053584%29.pdf)。','', 'NAV-RELPOSNED 在两机均存在。下表长度是其消息内 relPosLength，未与参考比较。其量级约为公里，并非 0.35 m；基准站 ID 也保留。因此不能把消息名称或 heading-valid 标志直接当作机载两天线短基线航向。全部 carrSoln、长度差分布及最大绝对偏差见 DG01_RELPOSNED.csv。','',table(overview_df,['sequence','receiver','NAV_epochs','RELPOS_median_m','RELPOS_heading_valid','RELPOS_refids']),'', '来源：DG01_OVERVIEW.csv 同序列/接收机行；相对长度为 m，valid 列是计数，分母为 NAV_epochs。','', '## D2. 单机质量与双 fixed 状态','',table(overview_df,['sequence','receiver','raw_epochs','raw_signal_rows','cno_p05','cno_median','cno_p95','lock_resets','cp_overflow','RINEX_LLI0']),'', '来源：DG01_OVERVIEW.csv；C/N0 单位 dB-Hz。后三列分别是 locktime 减小、cpStdev=15 的无效样本、RINEX LLI bit 0 事件，按不同卫星/信号累计，不能相加称为真实周跳。它们的每分钟率、各信号暴露量、C/N0×高度角箱和 NAV-SIG 载波使用/改正使用在 DG01_SIGNAL_QUALITY.csv。计数差异保留，不互相替代。','', 'NAV-PVT 的 hAcc 与 HPPOSECEF 的 pAcc 分开报告；接收机自报精度不是独立精度验证。参与载波且使用改正的卫星数来自 crUsed AND crCorrUsed，不推断内部已固定整数集合。','',table(fix,['sequence','metric','n','event_count','fraction','longest_s']),'', '来源：DG01_FIX_STATUS_TIMELINE.csv。agreement 行专指 v3 yaw_valid；三序列全部匹配且一致。NAV 闭窗分母与 RAWX 相差端点历元，是原始时标导致，未为匹配结果删行。BY2O 一机 float 时均为 GNSS2，GNSS1 在窗口内保持 fixed；出处 DG01_SIGNAL_QUALITY.csv 的 NAV_PVT/carrSoln 行。','', '![SFIG-DG1](SFIG-DG1.png)','', 'SFIG-DG1：两机逐历元 C/N0 中位数、跟踪卫星数及 NAV-PVT 载波状态。灰区为指定 BY2O 主段。原始波动照画，不平滑；RAWX 出现的卫星计为跟踪，不等同于 RTK 使用。','', '## D3. 两机一致性','',table(inter[inter.scope.isin(['paired_epochs','common_satellites_all'])],['sequence','scope','metric','n','median','p05','p95','min','max']),'', '来源：DG01_INTER_RECEIVER.csv。三个窗口的 RAWX rcvTow 标签差均为零，未配对数均为零；这只说明导出标签一致，不能证明硬件时钟、载波相位或接收链同步。C/N0 差和周跳指标同历元交并比逐信号完整列在该 CSV。','']
 sim=inter[(inter.metric=='raw_event_simultaneous')].groupby('sequence')[['both_count','union_count']].sum().reset_index();sim['intersection_over_union']=sim.both_count/sim.union_count
 blocks+=['同历元、同信号的 RAWX 事件（lock reset OR overflow）汇总如下；比例的分母是并集信号样本，非历元数。','',table(sim),'','## D4. 位置几何代理下的小数双差','', '按登记使用 HPPOSECEF 两机位置、广播轨道和原始载波。以下 residual=geometry−phase，采用 (−0.5,0.5] 周包裹；P95 列是绝对值分位。它没有使用方法输出的基线方向。非双方 fixed 的位置仅是较弱几何代理，不拿它证明固定解相位异常。','',table(dd,['sequence','gnss','signal','fix_group','n','median','p95_abs_cycles','frac_abs_gt025']),'', '来源：DG01_FRACTIONAL_DD.csv。系统编号 0=GPS、3=BeiDou、5=QZSS；信号编号保持 UBX 原码。完整直方图见图；所有稳定卫星/pivot 组合的 20 s 单元在 G: 的各序列 FRACTIONAL_STABILITY.csv.gz，汇总见 DG01_DD_STABILITY_SUMMARY.csv。','',table(stability[stability.fix_group=='both_fixed'],['sequence','gnss','signal','n_identity_time_cells','median_circular_sd','p95_circular_sd']),'', '上述圆离散是卫星/pivot/20 s 单元内部的变化，不能把合并直方图的偏峰直接说成恒定偏置。不同信号和组合有不同离散，存在时间变化；本任务没有估计或扣除相位偏置。','', '覆盖限制：使用的 HX02 Kepler 星历含 GPS/BeiDou/QZSS，未含 Galileo 星历记录；GLONASS 异频载波未强行按同波长整数 DD 处理，SBAS 也未进入该模型。它们仍进入 D1–D3 和可用的 CMC 统计，D4 不可计算计数留在 DD_UNAVAILABLE.json；不能把缺行解释成残差为零或跟踪失败。轨道计算另以 BY2 NAV-SAT 整数高度角作格式/符号核对，明细 ORBIT_SANITY_CHECK.csv，没有用该检查筛选结果。','', '![SFIG-DG2](SFIG-DG2.png)','', 'SFIG-DG2：各已具备几何输入信号的小数双差密度。蓝实线为双方 fixed，橙虚线为其他状态；后者只在有样本的 BY2O 出现。每列使用相同的包裹范围与固定分箱，不按数值删除信号。','', '## D5. CMC 与 BY2O 主段','',table(cm,['sequence','receiver','proxy','segment','n_finite_sd','median_sd_m','p95_sd_m']),'', '来源：DG01_CMC_OVERVIEW.csv，逐卫星/信号/高度角箱结果在 DG01_CMC.csv；单位 m。这里是各有限单元 SD 的中位/P95，非整个窗口单一 CMC SD。dual_frequency_MP 消一阶电离层后按连续弧去均值；single_frequency_linear 只去线性慢趋势。少于两个样本的弧不可计算。两者不混汇，也不是纯多径估计。primary 仅指 BY2O 指定主段，其他窗记 outside。不能由该表将多径、信号跟踪、位置代理与运动效应唯一分离。','', '## D6. RTKLIB 配置与既有 Q 状态','', '实际 RTKLIB 源码提交为 `180043ee24b6d2b168f98b64be15f69d50046b1a`。官方页面将 2.4.3 列为 beta；可核验的官方用户手册为 2.4.2，本报告未冒称读到独立 2.4.3 手册。配置含义以该手册与实际 options.c/rtkpos.c/rtkcmn.c 交叉核对。[官方版本说明](https://rtklib.com/)、[手册 E.7(7)](https://www.rtklib.com/prog/manual_2.4.2.pdf)。','']
 pivot=audit.pivot(index='option',columns='sequence',values='effective_value').reset_index();blocks+=[table(pivot),'', '来源：DG01_RTKLIB_CONFIG_AUDIT.csv，每序列每键均列原值、实际解释、缺省来源和对应 .conf。三个配置均显式给出 0.350 m 基线与 0.010 m sigma，因此“未配置长度约束”不符合文件事实。但 constbl 有协方差/非线性条件，缺运行残差日志，不能判定每历元真正应用了多少次。','', 'navsys=33 仅启用 GPS 与 BeiDou，GLONASS 没有被选入，gloarmode=off 不能单独作为低固定率原因。AR 为 continuous，非 fix-and-hold；arminfix 的设置不等于已经 hold。旧 pos1-snrmask 通过 searchopt 的字符串前缀匹配落到 rover 开关，不是被静默忽略；base 保持缺省关闭。没有依据结果改变任何 AR、SNR、高度角或动力学门限。','', 'RECOMMENDED_RTKLIB_MOVINGBASE_CONFIG.diff 仅建议将旧 SNR 键写成两个显式关闭开关、显式写出原有 hold 缺省、将未来残差日志开启；其余数值保持原样。该 diff 没有执行，也不承诺提高固定率。','',table(q,['sequence','Q','n_pos','n_Q','fraction_Q','n_nav_matched','both_fixed_n']),'', '来源：DG01_RTKLIB_Q_OVERLAP.csv。.pos 的条件分母仅是现有输出行，不能替代原生配对历元分母。Q=2 的大量输出同样落在两机各自 fixed 的时刻；二者是不同解算对象的状态标签。','',table(motion[(motion.grouping=='full')&(motion.method=='RTKLIB')],['sequence','n','valid_n','valid_fraction']),'', '来源：DG01_VALIDITY_MOTION.csv，RTKLIB/full。BY2O .pos 有一条 Q=1 的时间为 3186.000 s，对应原生表 3185.998 s，后者在闭窗外，所以两表分别为 113 与 112；详见 DG01_RTKLIB_BOUNDARY_ROWS.csv。未把差别当作失败或改写窗口。','', '![SFIG-DG3](SFIG-DG3.png)','', 'SFIG-DG3：双接收机 fixed 时间线与 RTKLIB 现有 .pos Q 状态。无 .pos 输出的时刻留空，不补成 Q=5。灰区为 BY2O 主段。','', '## D7. 有效历元的运动分布','',table(motion[motion.grouping=='motion'],['sequence','method','group','n','valid_n','valid_fraction']),'', '来源：DG01_VALIDITY_MOTION.csv；固定 20 s 时间段结果在同表 grouping=time20s。low_speed 是 GNSS 速度小于登记阈值；course_turning 是 GNSS course 差分，不是机体角速度，也没有测量步态。BY2O 的低速样本中 RTKLIB 没有有效历元；这与场景/接收状态共同变化，不能归因为静止本身。EXT01/EXT02 的 valid 也不能直接叫整数固定率。','', '## 数据支持的范围与执行记录','', '信号跟踪不一致：两机可见集合、C/N0 与事件计数存在差别，可由相应 CSV 逐信号查证；没有证明它是固定率的唯一原因。周跳：三个不同指示器都有计数，但不将 lock reset 或 cpStdev 溢出全算成已验证周跳。多径：提供去电离层/慢趋势后的代理量和高度角条件统计，没有独立多径观测。配置：明确记录星座、AR 模式、长度约束、旧键解析和日志缺口，没有运行替代配置，因果效果不能判定。','', '实现核对中修复了中间 CSV 的浮点保存精度、单点 CMC 弧的不可计算处理，以及无表头 GNSS18 的 yaw_valid 列位置：其为第 18 列（零基17），依据 clean5_parity/providers.py，不是位置有效位。登记中的“从表头识别”对该文件不适用，属于格式定位修正，没有更改 yaw_valid 定义或阈值。所有报告使用修正后的诊断输出。','', '图形 QA 在不修改库文件的前提下扩充了 dB-Hz/cycle/state 单位识别，补齐独立面板字母；修复字体不支持的上标字符。三图均机器 7/7，实际 PNG 3/3 检视通过，174 mm 宽，PNG 宽 4178 px，提供 PDF/SVG。系统 Axes3D 警告与本任务二维图无关。','', f'数据结构/哈希检查 {len(checks)}/{len(checks)}；机器图 QA {sum(x["pass"] for x in qa)}/{len(qa)}。报告生成时耗时 {elapsed:.2f} 分钟。scratch 的本任务字体缓存结束删除；仓库仅存汇总与图，逐历元明细在 G: DG01。INPUT_SHA256.json 和 OUTPUT_SHA256.json 分别登记输入/输出；不做交接包。结果提交与 push 的终态在回贴给出，以免提交自引用。','', '## 原始文件哈希','']
 pinrows=pd.DataFrame([dict(sequence=x['sequence'],receiver=x['receiver'],stream=x['stream'],sha256=x['actual']) for x in pins]);blocks+=[table(pinrows),'', '每行均为 RAW_FILE_HASH_LOCK.csv 与实际文件哈希一致；路径见 DG01_INPUT_SHA256.json，以 RAW_ROOT 相对路径展开。','', '## Inter-receiver ambiguity resolution on this platform','', 'The recorded receiver solution states and inter-receiver ambiguity outcomes describe different quantities. Both receivers reported fixed solutions throughout the BY2 and BY2H navigation windows. On BY2O, both were fixed at 1595 of 1886 navigation epochs, and the joint flag agreed with the retained heading-validity input. The exported RAWX epoch labels matched between receivers, but this does not establish physical clock or carrier-phase synchronization. Signal-level tracking, carrier-validity indicators, and fractional double differences varied between constellations and frequencies. Position-based geometric double differences retained non-zero fractional residuals even when both receiver solutions were fixed. These residuals and the detrended code-minus-carrier quantities are diagnostic proxies, not an identification of a unique error source. NAV-RELPOSNED messages were present, but their kilometre-scale lengths and recorded base-station identifier do not describe the robot’s short antenna separation. The retained RTKLIB configuration already specified a 0.350 m baseline constraint with a 0.010 m standard deviation. It selected GPS and BeiDou with continuous ambiguity resolution; GLONASS was excluded. The original paired-epoch fixed-output counts were 153/1370, 179/1350, and 112/1885. No alternative configuration was executed. Consequently, the observations document coexistence of receiver RTK fixing and sparse inter-receiver fixed output, while leaving the relative contributions of tracking, propagation, timing, geometry, and processing settings unresolved.','']
 eng=blocks[-2];nwords=len(re.findall(r"[A-Za-z0-9]+(?:[-’./][A-Za-z0-9]+)*",eng));assert 150<=nwords<=250,nwords
 (R/'DG01_REPORT.md').write_text('\n\n'.join(blocks).replace('\n\n\n\n','\n\n').rstrip()+'\n')
 log(f'REPORT English words {nwords}')
def main():
 overview();boundary();checks=validate()
 for p in [C/'01_RAW_HASH_LOCK/RAW_FILE_HASH_LOCK.csv',W/'configs/paper_rebuild/final_v23_parity_contract.yaml',W/'configs/paper_rebuild/clean5/CLEAN5_BY2H_SEQUENCE_CONTRACT.yaml',W/'configs/paper_rebuild/clean5/CLEAN5_BY2O_SEQUENCE_CONTRACT.yaml',W/'configs/paper_rebuild/v3/PROTOCOL_V3_CONTRACT.yaml',W/'src/legsa_gins/paper_rebuild/horizontal_literature/phase2_runner.py',W/'src/legsa_gins/paper_rebuild/horizontal_literature/shared_raw_backend.py']:read(p)
 save_sources();inputs=json.loads((O/'INPUT_SHA256.json').read_text());(R/'DG01_INPUT_SHA256.json').write_text(json.dumps({alias(k):v for k,v in inputs.items()},indent=2)+'\n');report(checks)
 for p in R.iterdir():
  if p.is_file():shutil.copyfile(p,O/p.name)
if __name__=='__main__':main()
