#!/usr/bin/env python3
"""Run PAPER10M1R2B provider generation plus effect validation.

The stage is intentionally generated by one deterministic driver so provider
files, validation tables, queue drafts, guard reports, and export-clean
material stay in sync.
"""

from paper10m1r2b_generate_by2_degraded_providers import main


if __name__ == "__main__":
    main()
